defaults:
  - logging: default
  - longevity: default
  - optimization: default
  - solver: default
  - case: default
  - hydra/sweep: basic
  - override hydra/sweep: flat
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override hydra/launcher: joblib
  - _self_

hydra:
  run:   # Sweep isn't needed because we're overriding above
    dir: results/${case.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra:job.id}
  job:
    chdir: true
    name: run
  launcher:
    n_jobs: 1
