case_name = "kim+sam-bequest"
description = "This is the case of Kim and Sam used as an example case for optimizing bequest and Roth conversions. A HFP file is associated with this case."

[basic_info]
status = "married"
names = [ "Kim", "Sam",]
date_of_birth = [ "1964-01-15", "1965-01-15",]
life_expectancy = [ 91, 93,]
start_date = "2026-01-01"
longevity_seed = 2004324345

[savings_assets]
taxable_savings_balances = [ 650.0, 250.0,]
tax_deferred_savings_balances = [ 1500.0, 500.0,]
tax_free_savings_balances = [ 60.0, 40.0,]
beneficiary_fractions = [ 1.0, 1.0, 1.0,]
spousal_surplus_deposit_fraction = 0.5

[household_financial_profile]
HFP_file_name = "Case_kim+sam-bequest_test2.xlsx"

[fixed_income]
pension_monthly_amounts = [ 0, 0,]
pension_ages = [ 65.0, 65.0,]
pension_indexed = [ false, false,]
social_security_pia_amounts = [ 3500, 2000,]
social_security_ages = [ 70.0, 68.0,]

[rates_selection]
heirs_rate_on_tax_deferred_estate = 33.0
dividend_rate = 1.75
obbba_expiration_year = 2032
method = "stochastic"
rate_seed = 2071076078
reproducible_rates = true
values = [ 12.53848, 10.00455, 8.39939, 5.0303,]
standard_deviations = [ 16.61002, 8.40866, 10.07218, 3.21505,]
correlations = [ [ 1.0, 0.46741, 0.3249, -0.28302,], [ 0.46741, 1.0, 0.84423, -0.55967,], [ 0.3249, 0.84423, 1.0, -0.38111,], [ -0.28302, -0.55967, -0.38111, 1.0,],]

[asset_allocation]
interpolation_method = "s-curve"
interpolation_center = 15.0
interpolation_width = 5.0
type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],], [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],],]

[optimization_parameters]
spending_profile = "flat"
surviving_spouse_spending_percent = 60
smile_dip = 15
smile_increase = 12
smile_delay = 0
objective = "maxBequest"

[solver_options]
netSpending = 145
maxRothConversion = 100
noRothConversions = "None"
startRothConversions = 2026
withMedicare = "optimize"
solver = "HiGHS"
spendingSlack = 0
xorConstraints = true
withSCLoop = true

[results]
default_plots = "today"
